name = "leverageai-network-website"
compatibility_date = "2024-01-01"

[env.production]
name = "leverageai-network-website-prod"
route = "https://leverageai.network/*"

[env.production.vars]
NODE_ENV = "production"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build"
cwd = "."
watch_dir = "app"

# Environment variables for production
[vars]
NODE_ENV = "production"

# Static asset configuration
[[build.upload]]
format = "service-worker"

# Headers for security and performance
[headers]
"/*" = [
  "X-Frame-Options: DENY",
  "X-Content-Type-Options: nosniff",
  "Referrer-Policy: strict-origin-when-cross-origin"
]
"/*.js" = [
  "Cache-Control: public, max-age=31536000, immutable"
]
"/*.css" = [
  "Cache-Control: public, max-age=31536000, immutable"
]
"/images/*" = [
  "Cache-Control: public, max-age=86400"
]